apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: autograde-sensor
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: autograding-event-dep
      eventSourceName: autograde-event-source
      eventName: autograde_events
  triggers:
    - template:
        name: autograde-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: autograde-workflow-
              spec:
                synchronization:
                  semaphore:
                    configMapKeyRef:
                      name: argo-config
                      key: PARALLEL_AUTOGRADING
                entrypoint: autograde-worker
                securityContext:
                  runAsNonRoot: true
                  runAsUser: 10001
                volumes:
                  - name: shared-pv-{{ .Release.Namespace }}
                    persistentVolumeClaim:
                      claimName: shared-pvc-{{ .Release.Namespace }}
                  - name: grader-pv-{{ .Release.Namespace }}
                    persistentVolumeClaim:
                      claimName: grader-pvc-{{ .Release.Namespace }}
                templates:
                  - name: autograde-worker
                    container:
                      image: illumidesk/grader-notebook:latest
                      imagePullPolicy: Always
                      command: [async_nbgrader]
                      args: ["process_message", "message"]
                      env:
                        - name: JUPYTERHUB_API_URL
                          valueFrom:
                            configMapKeyRef:
                              name: hub-illumidesk-cm
                              key: JUPYTERHUB_API_URL
                      volumeMounts:
                        - name: grader-pv-{{ .Release.Namespace }}
                          mountPath: /home
                          subPath: illumidesk-courses/{{ .Release.Namespace }}/home
                        - name: shared-pv-{{ .Release.Namespace }}
                          mountPath: /srv/nbgrader/exchange
                          subPath: {{ .Release.Namespace }}/exchange
          parameters:
            - src:
                dependencyName: autograding-event-dep
              dest: spec.templates.0.container.args.1
