apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  nats:
    exotic:
      url: nats://argo-events-nats.argo-events.svc:4222
      clusterID: argo-events-stan
