{{ if .Values.argo.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-config
  namespace: {{ .Release.Namespace }}
data:
  PARALLEL_AUTOGRADING: "{{ .Values.argo.autograding.concurrency | default 1 }}"

{{ end }}