{{ if .Values.argo.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    component: argo-rabbitmq
  name: argo-rabbitmq-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: main
      port: 5672
    - name: management
      port: 15672
  selector:
    app: argo-rabbitmq-task-queue
    component: argo-rabbitmq

---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: argo-rabbitmq
  name: argo-rabbitmq-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: argo-rabbitmq-task-queue
        component: argo-rabbitmq
    spec:
      containers:
        - image: rabbitmq:3.8.22-management-alpine
          name: argo-rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources:
            limits:
              cpu: 100m
{{ end }}