{{ if .Values.argo.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operate-workflow-sa-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operate-workflow-role-{{ .Release.Namespace }}
rules:
  - apiGroups:
      - argoproj.io
    verbs:
      - "*"
    resources:
      - workflows
      - workflowtemplates
      - cronworkflows
      - clusterworkflowtemplates
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operate-workflow-role-binding-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operate-workflow-role-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: operate-workflow-sa-{{ .Release.Namespace }}
    namespace: {{ .Release.Namespace }}
{{ end }}