{{ if .Values.illumideskSettings.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-agent-system-probe-config
  namespace: {{ .Values.datadog.namespace | default "kube-system" | quote }}
  labels: {}
data:
  system-probe.yaml: |
    system_probe_config:
      enabled: true
      debug_port:  0
      sysprobe_socket: /var/run/sysprobe/sysprobe.sock
      enable_conntrack: true
      bpf_debug: false
      enable_tcp_queue_length: false
      enable_oom_kill: false
      collect_dns_stats: false
      max_tracked_connections: 131072
      conntrack_max_state_size: 131072
    network_config:
      enabled: true
    runtime_security_config:
      enabled: true
      debug: false
      socket: /var/run/sysprobe/runtime-security.sock
      policies:
        dir: /etc/datadog-agent/runtime-security.d
      syscall_monitor:
        enabled: false

{{ end }}