{{ if .Values.allowNFS.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grader-pvc-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  volumeName: grader-pv-{{ .Release.Name }}
{{ if eq .Values.allowNFS.type "local" }}
  storageClassName: "local-storage"
{{ else if  eq .Values.allowNFS.type "efs" }}
  storageClassName: ""
{{ end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
{{ end }}