{{ if or (.Values.allowNFS.enabled) (.Values.allowLocal.enabled) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grader-pvc-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  volumeName: grader-pv-{{ .Release.Name }}
{{ if  .Values.allowLocal.enabled }}
  storageClassName: "local-storage"
{{ else if .Values.allowNFS.enabled }}
  storageClassName: ""
{{ end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.graderSetupService.storageRequests | default "200Mi" | quote }}
{{ end }}