{{ if .Values.illumideskSettings.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: hub-illumidesk-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  JUPYTERHUB_API_TOKEN: {{ .Values.illumideskSettings.jupyterhubAPIToken | default "a0e0c3e8ef678ea3bad91d5206e14a268f286c2fc4507c6c5402f9ab7074f721" | quote }}
  JUPYTERHUB_CRYPT_KEY: {{ .Values.illumideskSettings.jupyterhubCryptKey | default "58bba882a3defb4bcdf879b5eb2ea48e567d0ca8dfc11953bd37f9ab54c19d5a" | quote }}
  POSTGRES_NBGRADER_PASSWORD: {{ .Values.illumideskSettings.postgresGraderPassword | default "lA2lH0bE6hN8hE9y" | quote}}
  POSTGRES_JUPYTERHUB_PASSWORD: {{ .Values.illumideskSettings.postgresHubPassword | default "lA2lH0bE6hN8hE9y" | quote}}
  LTI_SHARED_SECRET: {{ .Values.illumideskSettings.ltiSharedSecret | default "lti_11_shared_secret" | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.illumideskSettings.oidcClientSecret | default "oidc_client_secret" | b64enc | quote }}
  SUPER_SECRET: {{ .Values.illumideskSettings.SUPER_SECRET | default "Abhilash Nair" | b64enc | quote }}

{{ end }}