{{ if .Values.illumideskSettings.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: hub-illumidesk-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  JUPYTERHUB_API_TOKEN: {{ .Values.illumideskSettings.jupyterhubAPIToken | default "" | b64enc | quote }}
  JUPYTERHUB_CRYPT_KEY: {{ .Values.illumideskSettings.jupyterhubCryptKey | default "" | b64enc | quote }}
  POSTGRES_NBGRADER_PASSWORD: {{ .Values.illumideskSettings.postgresGraderPassword | default "postgres" | quote}}
  POSTGRES_JUPYTERHUB_PASSWORD: {{ .Values.illumideskSettings.postgresHubPassword | default "postgres" | quote}}
  LTI_SHARED_SECRET: {{ .Values.illumideskSettings.ltiSharedSecret | default "" | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.illumideskSettings.oidcClientSecret | default "" | b64enc | quote }}
{{ end }}