{{ if .Values.illumideskSettings.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: illumidesk-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{ if .Values.externalDatabase.enabled }}
  postgresql-password:  {{ .Values.externalDatabase.databasePassword }}
{{ else if .Values.postgresql.enabled }}
  postgresql-password: {{ .Values.postgresql.postgresqlPassword }}
{{ end }}

{{ end }}