{{ if .Values.keyCloak.enabled }}
apiVersion:  v1
kind:  ConfigMap
metadata: 
  namespace:  {{ .Release.Namespace }}
  name:  keycloak-postgres-configmap-{{ .Release.Namespace }}
data:
  DB_SCHEMA: {{ .Values.keyCloak.db_schema | quote }}
  DB_USER: {{ .Values.keyCloak.db_user  | quote }}
  DB_DATABASE: {{ .Values.keyCloak.db_database  | quote }}
  DB_ADDR: {{ .Values.keyCloak.db_addr  | quote }}
  DB_VENDOR: {{ .Values.keyCloak.db_vendor | quote }}
  KEYCLOAK_USER: {{ .Values.keyCloak.keycloak_user | quote }}
  KEYCLOAK_PASSWORD: {{ .Values.keyCloak.keycloak_password }}
  DB_PASSWORD: {{ .Values.keyCloak.db_password }}




{{ end }}