#use this
{{ if .Values.nginxIngress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-{{ .Release.Name }}
  namespace:  {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy: default-src 'self' *;";
      more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains";
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Forwarded-Proto: https;"
spec:
  rules:
  - host: {{ .Values.nginxIngress.host }}
    http:
      paths:
        - path: /
          backend:
            serviceName: proxy-public
            servicePort: 80
        - path: /auth
          backend:
            serviceName: keycloak
            servicePort: 8080
{{ end }}
