apiVersion: v2
name: illumidesk
version: 0.0.1-n016.hebe045b
description: An extention of the JupyterHub chart with additional IllumiDesk resources
icon: https://configs.illumidesk.com/images/illumidesk-80.png
dependencies:
  - name: jupyterhub
    version: "0.9.1"
    repository: https://jupyterhub.github.io/helm-chart/
    import-values:
      - child: rbac
        parent: rbac
  - name: postgresql
    version: "9.8.6"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  # - name: nfs-server-provisioner
  #   version: "1.1.1"
  #   repository: https://kubernetes-charts.storage.googleapis.com  
  #   condition: nfs-server-provisioner.enabled
maintainers:
  - name: IllumiDesk Team
    email: hello@illumidesk.com
