apiVersion: v2
name: illumidesk
version: 0.1.0
appVersion: 0.1.0
description: An extention of the JupyterHub chart with additional IllumiDesk resources
icon: https://configs.illumidesk.com/images/illumidesk-80.png
dependencies:
  - name: jupyterhub
    version: "0.10.2"
    repository: https://jupyterhub.github.io/helm-chart/
    import-values:
      - child: rbac
        parent: rbac
  - name: postgresql
    version: "9.8.6"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: datadog
    version: "2.4.29"
    repository: https://helm.datadoghq.com
    condition: datadog.enabled
maintainers:
  - name: IllumiDesk Team
    email: hello@illumidesk.com