apiVersion: v2
name: illumidesk
version: 0.0.1-set.by.chartpress
description: An extention of the JupyterHub chart with additional IllumiDesk resources
dependencies:
  - name: jupyterhub
    version: "0.9.0"
    repository: 'https://jupyterhub.github.io/helm-chart/'
    import-values:
      - child: rbac
        parent: rbac
maintainers:
  - name: IllumiDesk Team
    email: hello@illumidesk.com
