# IllumiDesk configuration values
# --------------------
# Create and use roles and service accounts on an RBAC enabled cluster.
rbac:
    enabled: true
  
jupyterhub:
# Helm config for jupyterhub goes here
# See https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/values.yaml

    singleuser:
      image:
        name: illumidesk/base-notebook:latest
        tag: 2020.08.27
      defaultUrl: "/tree"
    prePuller:
      hook:
        enabled: false
    # optimizations: see https://zero-to-jupyterhub.readthedocs.io/en/latest/optimization.html?highlight=scheduling#optimizations
    scheduling:
      userScheduler:
        enabled: true
        replicas: 2
      podPriority:
        enabled: true
      userPlaceholder:
        enabled: true
        replicas: 2
    traefik:
      service:
        # Not meant to be exposed to the public directly with this setup
        type: ClusterIP