chart-dirs:
  - docs
chart-repos:
  - illumidesk=https://charts.illumidesk.com/docs
check-version-increment: true
debug: true
remote: origin
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true