chart-repos:
  - illumidesk=https://illumidesk.github.io/helm-chart
  - jupyterhub=https://jupyterhub.github.io/helm-chart/
  - bitnami=https://charts.bitnami.com/bitnami
  - datadoghq=https://helm.datadoghq.com
  - argo=https://argoproj.github.io/argo-helm
target-branch: main
debug: true
remote: origin
validate-chart-schema: true
validate-yaml: true
validate-maintainers: false
