apiVersion: v2
name: illumidesk
version: 5.5.0
appVersion: 1.2.0
description: An extention of the JupyterHub chart with additional IllumiDesk resources
icon: https://configs.illumidesk.com/images/illumidesk-80.png
dependencies:
  - name: jupyterhub
    version: "1.1.1"
    repository: https://jupyterhub.github.io/helm-chart/
    import-values:
      - child: rbac
        parent: rbac
maintainers:
  - name: IllumiDesk Team
    email: hello@illumidesk.com
