apiVersion: v2
name: illumidesk
version: 5.11.5
appVersion: 1.3.0
description: An extention of the JupyterHub Chart with additional IllumiDesk resources
icon: https://configs.illumidesk.com/images/illumidesk-80.png
dependencies:
  - name: jupyterhub
    version: "1.1.1"
    repository: https://jupyterhub.github.io/helm-chart/
    import-values:
      - child: rbac
        parent: rbac
  - name: postgresql
    version: "10.16.1"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
maintainers:
  - name: IllumiDesk Team
    email: hello@illumidesk.com
