{{ if .Values.albIngressController.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller-{{ .Release.Name }}
  name: alb-ingress-controller-{{ .Release.Name }}
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - configmaps
      - endpoints
      - events
      - ingresses
      - ingresses/status
      - services
      - pods/status
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
  - apiGroups:
      - ""
      - extensions
    resources:
      - nodes
      - pods
      - secrets
      - services
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller-{{ .Release.Name }}
  name: alb-ingress-controller-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alb-ingress-controller-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: alb-ingress-controller
    namespace: {{ .Release.Namespace }}
---

{{ if .Values.albIngressController.enableIRSA }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  annotations:
    {{- range $key, $value := .Values.albIngressController.serviceAccount.annotations }}
      {{ $key }} : {{ $value }}
    {{- end }}
  name: alb-ingress-controller
  namespace: {{ .Release.Namespace }}
...
{{ end }}
{{ end }}