{{ if .Values.albIngressController.enabled }}
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: {{ .Values.albIngressController.awsAccessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.albIngressController.awsSecretToken | b64enc }}
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: secrets-{{ .Release.Name }}
type: Opaque
{{ end }}