{{ if .Values.allowEFS.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-shared-volume
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: {{ .Values.allowEFS.efs }}
    path: printf "/mnt/efs/fs1/%s" .Values.allowEFS.orgName

{{ end }}


  