{{ if .Values.allowNFS.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.Release.Name }}-grader-pvc
  namespace: {{ .Release.Namespace }}
spec:
  volumeName: {{.Release.Name }}-grader-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 11Gi
{{ end }}