{{ if .Values.allowNFS.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  #name: {{ .Release.Name}}-exchange-shared-volume
  name: exchange-shared-volume
  namespace:  {{.Release.Namespace }}
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
{{ end }}