
{{ if .Values.allowNFS.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  volumeName: shared-pv-{{ .Release.Name }}
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 11Gi
{{ end }}